version: '3.8'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "9091:8081"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./shared-volume:/home/jenkins
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./shared-volume:/home/nginx/report # Monte le répertoire des artefacts Jenkins dans NGINX
      - ./nginx.conf:/etc/nginx/nginx.conf  # Fichier de configuration NGINX
    restart: unless-stopped

volumes:
  nexus-data:
    external: true
    name: nexus-data
  jenkins_home:
    external: true
    name: jenkins_home
