version: '3.8'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "9091:8081"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - gradle_volume:/opt/gradle
      - ./shared-volume:/home/jenkins
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9092:80"
    volumes:
      - ./shared-volume:/home/nginx/report
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: unibankbackend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
      build: .
      depends_on:
        - postgres
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/unibankbackend
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: root
      ports:
        - "9090:9090"

volumes:
  nexus-data:
    external: true
    name: nexus-data
  jenkins_home:
    external: true
    name: jenkins_home
  gradle_volume:
    external: true
    name: gradle_volume
  postgres_data:


